M48
; DRILL file KiCad 10.0.4 date 2026-08-19T21:03:10
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-19T21:03:10-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X144.39Y-75.18
X149.24Y-75.18
T2
X144.09Y-72.15
X149.54Y-72.15
M30
